### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by Bisaloo** [Stan125/limoaddin#1]
It's near to impossible to understand what your code does without installing it if you don't provide a readme with: 
- why?
- how to install?
- minimal working example **with screenshots**

This could possibly get of lot of interest given how recent addins are and the buzz that I foresee about it. But I am pretty sure no one will install anything without a (at least short) description.

**Comment by Stan125** [comment]
Thank you for your input! :+1:  As a GitHub newbie, any help is much appreciated. I just updated the package with a little description.
